### ISSUE TITLE
Better define validateBasic role in dymint

### ISSUE THREAD

**Issue by omritoptix** [dymensionxyz/dymint#1112]
Currently we agreed on assuming  that whatever passes `ValidateBasic` on dymint, and fails on stateful validation, is subjected to fraud.
This basically means that `ValidateBasic` should at least verify that the current sequencer, as known by the node, signed the block.

This could potentially pose issues with sequencer rotation, assuming blocks are rejected even though they belong to current sequencer but current node doesn't know yet it's the next sequencer.

on the other hand, if the node doesn't know, he can't apply it either way, so it may be just a random block from a random 3rd party. 

I'm not sure there is a real issue with that but just in case we should better define the role of ValidateBasic and make sure it's call sites are well defined and align with our current detection flow.

**Comment by srene** [comment]
Commit `ValidateWithHeader` func, is already being executed at p2p_validator, so anything received from gossipsub will be checked for current proposer signature, and also when its applied in `validateBlockBeforeApply` func.

This could be moved inside a generate validateBasic function, so it is always called when doing basic validation on a block.

However i see two issues that could happen currently in dymint regarding signature validation:
- blocksync is currently is not doing block validation on reception, which means if an attacker is sending wrong blocks, it could affect syncing performance (blocks will be rejected afterwards when applying, but will be marked initially as received), and putting nodes in unhealth status.
- for sequencer rotation, dymint is not aware of the active proposer per height, but the last active proposer. which means that when there is a sequencer rotation, nodes at previous heights will not be able to sync because signature validation will fail.
