### ISSUE TITLE
Duplicate consensus msgs upon sequencer reboot 

### ISSUE THREAD

**Issue by omritoptix** [dymensionxyz/dymint#1175]
once sequence reboots, we will generate duplicate consensus msgs as we don't persist the last state of the sequencer we saw in state. in case the sequencer is in a restart loop this can nasty.

**Comment by keruch** [comment]
It is impossible (or at least hardly feasible) to persist the sequencer set in both full node and proposer modes because we need to persist not the latest sequencer set but the one we had while applying the latest block. And in full node mode we cannot get this unless the proposer persists this info into the block. Finally, I came up with storing two versions of the sequencer set:
1. The latest set that we get from polling: Store it in memory and use it for both modes.
2. The last block sequencer set: the one we used while producing the last block. Store it in the store while producing blocks in the proposer mode.

Now the proposer will create consensus messages during block production based on the difference between these two sets.

On reboots:
1. The proposer gets the last set from the Hub.
2. While producing the block, get the last block set from the store.
3. Memorize the current set (from memory == from Hub).
4. Compute diff and create consensus messages.
5. If the block production is successful, save the memorized set from (3) as the last block set (and use it on the next production).

The only drawback is that the full node does not persist in the sequencer set, so on rotation it will duplicate consensus messages, but only once.
