### ISSUE TITLE
gossip blocks

### ISSUE THREAD

**Issue by omritoptix** [dymensionxyz/dymint#12]
## Overview

Currently full nodes are only aware of new blocks upon submission to the hub.

## Problem

**High latency** - if a light client is connected to a non-sequencer full node, it will only get a tx response when a batch is submitted which causes a huge tx response time for light clients connected to non-sequencer full node. 
**DDOS vector** - For a [sentry architecture](https://forum.cosmos.network/t/sentry-node-architecture-overview/454) (for DDOS protection) we will want the ability to position full nodes in a public subnet which communicate with the sequencer over a private connection.

## Possible solution

Gossip the block and its commit before writing the batch to the hub.

### Pros
1. Reduce load from the sequencer both in check tx validation time and num of connections. 
3. Support for sentry architecture.
### Cons
1. Higher tx latency. Especially if multiple hops are involved. 
2. Require more validation strategies and possible rollback as the full nodes are updated with blocks in an optimistic way (and not directly from the hub). 

## Current assumption
All gossiped blocks  are valid (i.e trusted sequencer) 

## TODO
Handle the case where the blocks gossiped are different then the block registered on the DA

## Disclaimer

There are multiple ways to mitigate DDOS attacks and maintain a high SLA. The decisions on which route to take are the responsibility of the sequencer operator and they will be slashed for downtime. We want to make sure though we provide the sequencer operator with a flexible DDOS strategy by allowing block gossiping. 

## Dependencies

- [x] #156 
- [x] #157  
- [x] #159 
- [x] #158

**Comment by shaolin-flow** [comment]
>Require more validation startegies and possible rollback as the full nodes are updated with blocks in an optimistic way (and not directly from the hub).

#### Overview
Sequencers may double-sign valid blocks at the same height, gossiping one version p2p and publishing another to the DA. The `source` field indicates whether the block originated p2p from the sequencer or from the DA. The DA publication takes precedence over the canonical ordering of the blocks. As such, non-aggregator full nodes can always sync to the correct chain. 


#### Questions
1. Is the following double-sign node misbehavior handled similar to Tendermint?
2. I believe you are referring to this as `optimistically` because the potential for double-signing. Full nodes download the transactions and should reach the same state root, if not then there was an invalid transaction/non-published transaction. Is it correct that `optimistic` here relates to potential double-signing rather than not downloading the gossiped block.
