### ISSUE TITLE
Change to use rpc client as api gateway is gonna get deprecated for writing to celestia

### ISSUE THREAD

**Issue by omritoptix** [dymensionxyz/dymint#398]
quoting celestia core developer:

The HTTP API or Gateway will soon become read-only and will only accept signed transactions, meaning that the sender will know the hash even before sending.

Why remove? The gateway is meant to be deployed by infra providers to enable public access to DA network for those who don't want or can't run(like browsers currently). For all other use cases where you can run your node, people should use private RPC with auth. It will have signing capabilities and much more useful APIs, like BlobModule for example. 

So ideally you would start migrating to RPC already(I think Rollkit already doing some work towards that).

Note:
Rollkit already migrated so we can have a look there.

**Comment by mtsitrin** [comment]
Subtasks:

- [ ] `celestia` - patch to use `arabica-9` and apply hotfix of `rc6.1`
- [ ] `roller`
  - [ ] wait till da light client is synced before running sequencer
  - [ ] supply `auth_token` and update namespace for sequencer da_config
  - [ ] use default rpc port instead of rest port
  - [ ] update install script
  - [ ] migration
- [ ] `dymint`
  - [ ] use rpc instead of rest
  - [ ] update namespace length
  - [ ] validate inclusion (get commitment/proof)
  - [ ] update UT
