### ISSUE TITLE
gasLimit should be checked when creating the batch

### ISSUE THREAD

**Issue by mtsitrin** [dymensionxyz/dymint#418]
currently, when creating the batch, we check only for `maxSizeInBytes`, i.e that the batch isn't too large in size
We probably should check the expected gas for the batch is also beneath the gasLimit

**Comment by omritoptix** [comment]
As I see it, it wouldn't matter match.

we dont check that the `maxSizeInBytes` fits to the DA Layer limits, we just let the user set it and check it's not large enough compared to what the user set - however it may still be too big for the DA layer.

if it will fail, the error will be propogated.

Similiarily we let the user set the GasLimit. so I don't think there is added value of checking it as the GasLimit may change between da layer upgrades and in that case we anyway need to check it before any submit and in that case it's similar to failing to send.

**Comment by mtsitrin** [comment]
our triggers to create and send a batch:
1. Timeout (max_submission_timeout)
2. Num of blocks

when creating the batch, it will use all the available blocks in queue (or until MaxSizeInBytes)

But it might be that the created batch, will have estimated Gas higher that the Gas Limit provided

**Comment by omritoptix** [comment]
I understand, but I think it's there is no practical solution for that. 

In order to get the real estimated gas we'll need to simulate the tx (as every change in the base layer code can change the calculation + it's more accurate). 

Currently we calculate the gas price of Celestia manually, but Celestia is gonna add a way to estimate the gas/fees using a tx simulation which is done before the submission and will be much more accurate hence will save costs for the operator (as all the gas is consumed, regardless to how much is used). 

I believe other DA will supply the same simulation mechanism (similar to how the hub works).

Simulating it for every possible batch size until you hit the limit is unpractical due to the time it takes. 

As I see it we should let the operator set it's desired params and  alert about the batch failing to submit with the relevant errors and than decide if he wants to:
1. decrease batch size/time
2. Increase gas Limit 
3. etc..

**Comment by omritoptix** [comment]
@mtsitrin can this be closed?
