### ISSUE TITLE
Invalid blocks can be received via p2p gossip

### ISSUE THREAD

**Issue by omritoptix** [dymensionxyz/dymint#656]
In block/manager.go:256-278, the applyBlockCallback callback function is called
whenever a new block is received via libp2p gossip. If the received block height is equal to
the next expected height, the block is applied via the applyBlock function in line 269.
Otherwise, if the block height is for a future height, the block and the corresponding commit
are stored in prevBlock and prevCommit, respectively.
However, at this point, the block is not yet validated by verifying the signature to ensure the
sequencer has produced it. This stateful check is only performed later in the executeBlock
function in block/block.go:180-182 via the Validate function.
As a result, invalid blocks can be received and processed by nodes

**Comment by srene** [comment]
i'm not sure why is this an issue. If invalid blocks are cached without validation, because there is a missing block, they will be validated later on, once the missing block is received, and discarded if not valid. ValidateProposedTransition function will fail if not called with the block for the next height, so it cannot be called at the moment of reception. I'm not sure what is the attack vector if blocks are cached without validation, taking into account that at the moment the missing block is received, the previously cached blocks will be validated and discarded if not valid, and also considering that gossiping will deliver all blocks under the assumption full-nodes are connected to at least one honest node.

**Comment by danwt** [comment]
Yeah it's probably not a big problem
But correct blocks in cache can be overwritten by receiving incorrect ones

**Comment by srene** [comment]
one thing i think needs to be done to easily avoid lots of potential issues regarding p2p gossiping is to change the p2p validation function (which is called for every gossiped block received) to something more advanced compared to what is used now, that is just checking basic validation (the block is well formed). one easy thing to do, i guess, would be to check that the block comes from the proposer, and it will avoid anyone injecting packets in the network, or caching packets that are not coming from the sequencer.

**Comment by danwt** [comment]
yeah for sure we need some kind of validation function

we ought to be careful to make something that will be easy to upgrade when proposer rotation is released

**Comment by srene** [comment]
This PR https://github.com/dymensionxyz/dymint/pull/737 solves the issue, by checking the block is singed by the sequencer
