### ISSUE TITLE
Pending blocks are repeatedly gossiped

### ISSUE THREAD

**Issue by omritoptix** [dymensionxyz/dymint#660]

**Comment by danwt** [comment]
So, this issue is about gossiping here 

https://github.com/dymensionxyz/dymint/blob/df192a9904800b7b1a8bf60a17987cd6630fe5f7/block/produce.go#L156-L159

when the block was loaded here 

https://github.com/dymensionxyz/dymint/blob/df192a9904800b7b1a8bf60a17987cd6630fe5f7/block/produce.go#L107-L116

but blocks are only loaded, I believe, as a crash recovery mechanism

Therefore this is a very edge case, and the only negative impact is a slight duplication in gossiped blocks

I suggest we mark this 'wont fix' and close

Unless The block l107-l116 is also for another reason
