### ISSUE TITLE
sequencer is failing to close the gap between the batch submitted height and the block produced height

### ISSUE THREAD

**Issue by srene** [dymensionxyz/dymint#959]
sequencer seems to fail to submit multiple batches, when it is required because the last submitted batch is far behind the last block produced, when batch submission is triggered by size.
Also, when a node is restarted, it does not take into account last batch submitted height, and it will take another max_batch_size to submit.

**Comment by danwt** [comment]
> i think the issue comes from the fact the stored blocks that arere not sumbitted are not counted on restart
so these blocks keep accumulating after each restart but not counted on the accumulated size (edited) 
and there is a gap between the last block produced and last block submitted that keeps growing with each restart, when the blocks are produced constantly and batches are produced because of max batch size limit
